/*
  Warnings:

  - The values [REVENUE_TOTAL,REVENUE_MONTHLY,REVENUE_DAILY,AVERAGE_ORDER_VALUE,USER_COUNT_TOTAL,USER_COUNT_ACTIVE,USER_COUNT_NEW,USER_RETENTION_RATE,USER_CHURN_RATE,SUBSCRIPTION_COUNT_TOTAL,SUBSCRIPTION_COUNT_ACTIVE,SUBSCRIPTION_COUNT_NEW,SUBSCRIPTION_COUNT_EXPIRED,SUBSCRIPTION_COUNT_CANCELLED,SUBSCRIPTION_CONVERSION_RATE,SUBSCRIPTION_RENEWAL_RATE,PAYMENT_COUNT_TOTAL,PAYMENT_COUNT_SUCCESSFUL,PAYMENT_COUNT_FAILED,PAYMENT_COUNT_PENDING,PAYMENT_SUCCESS_RATE,PAIR_COUNT_TOTAL,PAIR_PERFORMANCE_AVG,PAIR_POPULARITY,AUDIT_LOG_COUNT,NOTIFICATION_COUNT,EVENT_COUNT,COMMISSION_TOTAL,AFFILIATE_COUNT,REFERRAL_COUNT,CUSTOM] on the enum `StatsType` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `isActive` on the `User` table. All the data in the column will be lost.

*/
-- CreateEnum
CREATE TYPE "public"."UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED');

-- AlterEnum
BEGIN;
CREATE TYPE "public"."StatsType_new" AS ENUM ('FILE_METRICS', 'USER_METRICS', 'AFFILIATE_METRICS', 'REVENUE_METRICS', 'SUBSCRIPTION_METRICS', 'BILLING_METRICS', 'COMMISSION_METRICS', 'PAYMENT_METRICS', 'PAYOUT_METRICS', 'NOTIFICATION_METRICS', 'AUDIT_METRICS', 'EVENT_METRICS', 'EMAIL_METRICS');
ALTER TABLE "public"."Stats" ALTER COLUMN "type" TYPE "public"."StatsType_new" USING ("type"::text::"public"."StatsType_new");
ALTER TYPE "public"."StatsType" RENAME TO "StatsType_old";
ALTER TYPE "public"."StatsType_new" RENAME TO "StatsType";
DROP TYPE "public"."StatsType_old";
COMMIT;

-- AlterTable
ALTER TABLE "public"."User" DROP COLUMN "isActive",
ADD COLUMN     "status" "public"."UserStatus" NOT NULL DEFAULT 'ACTIVE';
